# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wb75r-9tR-jJ8Ir7KYbSu6zg073o1GWU
"""

import pandas as pd

df=pd.read_csv("booking.csv")

df

